apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-config
  namespace: demo-blog
data:
  BLOG_TITLE: "Le Blog de dylan"
  BLOG_SUBTITLE: "Mes aventures GitOps"
  AUTHOR: "dylan"
  VERSION: "1.0.0"
